# Generated by Django 5.2.8 on 2026-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hyper_Local_Weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherreading',
            name='air_quality',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
