# Generated by Django 5.2.8 on 2026-04-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hyper_Local_Weather', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(default='Defaults/Default-profile.jpg', max_length=255),
        ),
    ]
