# Generated by Django 5.2.8 on 2026-04-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hyper_Local_Weather', '0004_remove_profile_image_profile_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar_url',
            new_name='image',
        ),
    ]
