# Generated by Django 4.2.30 on 2026-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hyper_Local_Weather', '0005_rename_avatar_url_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Defaults/Default-profile.jpg', upload_to='profile_pics/'),
        ),
    ]
