# Generated by Django 6.0.4 on 2026-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hyper_Local_Weather', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_success_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_tips_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
